server:
  port: 8080



spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/usuario/**


eureka:
  client:
   register-with-eureka: false 
   fetch-registry: false